import Std
import Init.Grind.Ordered.Module
import Definitions.Def_CollatzWork_QuarterGapStatement
import Definitions.Def_CollatzWork_QuarterGapUniversalStatement
import Theorems.Thm_CollatzWork_mechanical_twelve_propagation



theorem CollatzWork.mechanical_large_bound : MechanicalSixteenEnvelopeStatement := by sorry

