"""Apply manually reviewed prose only; never rewrite any Lean payload bytes."""
import json
from pathlib import Path

ROOT = Path(__file__).parent
REVIEW = {}
T = r"Let $T:\mathbb N\to\mathbb N$ be the shortcut Collatz map: $T(n)=n/2$ for even $n$ and $T(n)=(3n+1)/2$ for odd $n$. Write $T^k$ for its $k$-fold iterate, with $T^0(n)=n$."
O = r"Let $C:\mathbb N\to\mathbb N$ be the ordinary Collatz map: $C(n)=n/2$ for even $n$ and $C(n)=3n+1$ for odd $n$. Write $C^k$ for its $k$-fold iterate."
CONV = r"Write $\mathcal C(n)$ for the assertion that $T^j(n)=1$ for some $j\in\mathbb N$."
MECH = r"For $s\in\mathbb N$, define $M(0)=0$, $M(s+1)=3M(s)+2^{\lfloor\log_2(3^s)\rfloor}$, and $e(s)=\lfloor\log_2(3^s)\rfloor+1$."
ORBIT = r"Let $q_k(n)$ count the odd inputs among the first $k$ shortcut steps, and let $R_0(n)=0$; recursively $R_{k+1}(n)=R_k(n)$ for an even input $T^k(n)$ and $R_{k+1}(n)=3R_k(n)+2^k$ for an odd input."
FIRST = r"A first coefficient contraction at time $k$ means $k>0$, $3^{q_k(n)}<2^k$, and $2^j\le3^{q_j(n)}$ for every $j<k$. Its existence is a hypothesis."
FINITE = "These are finite-orbit arithmetic results. They do not establish universal Collatz convergence, and this import makes no mathematical priority claim."

def add(name, title, assumptions, formula, role, proof, context=""):
    if not name.startswith(("CollatzWork.", "BlindCollatz.")):
        name = "CollatzWork." + name
    text = "\n\n".join(x for x in [context, assumptions, "$$\n" + formula + "\n$$", role] if x)
    REVIEW[name] = {"title": title, "statement": text,
                    "explanation": "\n\n".join(x for x in [context, assumptions, "$$\n" + formula + "\n$$", proof] if x)}

for n in ["affineRecurrenceTelescope", "BlindCollatz.RepetitionBound.telescope"]:
    add(n, "Telescoping a finite multiplicative recurrence", r"Let $a,b,k\in\mathbb N$ and $y:\mathbb N\to\mathbb N$. Assume $b y_{i+1}=a y_i$ for every $i<k$. Then", r"b^k y_k=a^k y_0.", "This records the exact accumulated multiplier without division or positivity assumptions.", "Induct on the number of recurrence equations. Multiply the induction identity by the next multiplier and substitute the final recurrence equation; associativity collects the powers.")
add("fixedRatioDivisibility", "Denominator divisibility under a fixed coprime recurrence", r"Let $a,b,k\in\mathbb N$, $\gcd(b,a)=1$, and $y:\mathbb N\to\mathbb N$. If $b y_{i+1}=a y_i$ for all $i<k$, then", r"b^k\mid y_0.", "The conclusion measures the initial divisibility needed to sustain a fixed rational multiplier.", r"The telescoping child lemma gives $b^k y_k=a^k y_0$. Hence $b^k$ divides $a^k y_0$. Coprimality of the two powers cancels $a^k$ from this divisibility.")
add("finiteRepetitionBound", "Finite repetition bound for a positive initial value", r"Let $a,b,k\in\mathbb N$, $\gcd(b,a)=1$, and $y:\mathbb N\to\mathbb N$ with $y_0>0$. If $b y_{i+1}=a y_i$ for every $i<k$, then", r"b^k\le y_0.", "This bounds repetitions of one fixed multiplier; it imposes no common budget on changing multipliers.", "The denominator-divisibility child gives that the denominator power divides the positive initial value. A divisor of a positive natural number is at most that number.")
add("noInfinitePositiveRecurrence", "A fixed coprime denominator cannot recur forever", r"Let $a,b\in\mathbb N$ satisfy $\gcd(b,a)=1$ and $b>1$, and let $y:\mathbb N\to\mathbb N$ satisfy $y_0>0$. Then", r"\neg\bigl(\forall i\in\mathbb N,\ b y_{i+1}=a y_i\bigr).", "This excludes an infinite sequence obeying this single recurrence, rather than arbitrary sequences of different affine blocks.", r"If the recurrence held at every index, the finite-bound child applied with $k=y_0$ would give $b^{y_0}\le y_0$. For $b>1$ the elementary power bound gives the strict reverse inequality.")
for n in ["affineRepetitionBound", "BlindCollatz.RepetitionBound.affine_repetition_bound"]:
    add(n, "Divisibility budget for a repeated affine block", r"Let $b,d,c,k\in\mathbb N$ with $\gcd(b,b+d)=1$, and $x:\mathbb N\to\mathbb N$ with $d x_0+c>0$. Assume $b x_{i+1}=(b+d)x_i+c$ for every $i<k$. Then", r"b^k\le d x_0+c.", "The positive shifted initial value bounds repetitions of a fixed affine rule. Degenerate parameters remain covered when they satisfy the stated hypotheses.", r"Set $y_i=d x_i+c$. Multiplying the affine equation by $d$ and adding $bc$ gives $b y_{i+1}=(b+d)y_i$. Apply the finite coprime-multiplier bound to this shifted sequence.")
for n in ["noInfiniteExpandingAffineBlocks", "BlindCollatz.RepetitionBound.no_infinite_expanding_affine_blocks"]:
    add(n, "Exclusion of an infinitely repeated affine block", r"Let $b,d,c\in\mathbb N$ with $\gcd(b,b+d)=1$ and $b>1$, and let $x:\mathbb N\to\mathbb N$ satisfy $d x_0+c>0$. Then", r"\neg\bigl(\forall i\in\mathbb N,\ b x_{i+1}=(b+d)x_i+c\bigr).", "Only the displayed fixed block is excluded; this does not exclude every nonconvergent Collatz itinerary.", r"The shift $y_i=d x_i+c$ turns the affine recurrence into the fixed multiplicative recurrence $b y_{i+1}=(b+d)y_i$. Its initial value is positive, so the no-infinite-recurrence result applies.")
add("BlindCollatz.RepetitionBound.alternating_repetition_bound", "Finite budget for the alternating expansion recurrence", r"Let $x:\mathbb N\to\mathbb N$ and $k\in\mathbb N$. If $8x_{i+1}=9x_i+5$ for every $i<k$, then", r"8^k\le x_0+5.", "This specializes the fixed affine-block budget to the alternating expansion parameters.", "Apply the affine repetition bound with denominator 8, increment 1, and offset 5. The coprimality and shifted positivity hypotheses hold for every natural initial value.")
add("BlindCollatz.RepetitionBound.no_infinite_alternating_blocks", "The alternating expansion recurrence cannot hold forever", r"For every sequence $x:\mathbb N\to\mathbb N$,", r"\neg\bigl(\forall i\in\mathbb N,\ 8x_{i+1}=9x_i+5\bigr).", "Arbitrarily long finite blocks can coexist with the impossibility of one infinite fixed-block orbit.", "Specialize the no-infinite-affine-block theorem to denominator 8, increment 1, and offset 5; the shifted initial value is always positive.")
add("prefixReturnBernoulli", "Integral Bernoulli bound for the ratio 32 over 27", r"For every $d\in\mathbb N$,", r"(27+5d)27^d\le27\cdot32^d.", "This is a denominator-cleared Bernoulli estimate used in conditional repetition budgets.", r"Induct on $d$. In the induction step use $27(32+5d)\le32(27+5d)$, multiply by $27^d$, and apply the induction hypothesis.")
add("prefixReturnNumericalBound", "Linear budget from an exponential return inequality", r"Let $n,d\in\mathbb N$ satisfy $2\cdot32^d<27^d(n+1)$. Then", r"10d+27<27n,\qquad d\le\left\lfloor\frac{27n-28}{10}\right\rfloor.", "The exponential inequality is an explicit premise; applications to any particular orbit must establish it separately.", r"Combine the integral Bernoulli child with the assumed strict exponential bound. Cancel the positive factor $27^d$, obtaining $2(27+5d)<27(n+1)$. Integer arithmetic gives both conclusions. Natural subtraction in the displayed bound is truncated; the premise supplies the needed positive range.")

add("BlindCollatz.descent_iff_convergence", "Ordinary Collatz convergence is equivalent to universal descent", r"Universal descent means that each $n>1$ has a positive time $k$ with $C^k(n)<n$. Then", r"\bigl(\forall n>1,\ \exists k>0,\ C^k(n)<n\bigr)\iff\bigl(\forall n>0,\ \exists j\in\mathbb N,\ C^j(n)=1\bigr).", "This is an equivalence of two unproved universal assertions, not a proof of either assertion.", "Convergence implies descent by using the iterate reaching 1. Conversely, strong induction sends each start above 1 to a strictly smaller positive iterate, applies convergence there, and concatenates the two finite trajectories.", O)
add("converges_shortcutIter_iff", "Convergence is invariant under a finite shortcut prefix", r"For all $r,n\in\mathbb N$,", r"\mathcal C(T^r(n))\iff\mathcal C(n).", "The statement concerns reaching 1; the shortcut orbit of 1 continues around the 1–2 cycle.", "One direction concatenates finite iterates. For the other, compare the prefix length with a time at which the original orbit reaches 1. Before that time use the remaining suffix; after it use convergence of every finite iterate of 1.", T+" "+CONV)
add("converges_iff_of_coalesces", "Coalescing shortcut orbits converge equivalently", r"Let $n,m,r,s\in\mathbb N$ satisfy $T^r(n)=T^s(m)$. Then", r"\mathcal C(n)\iff\mathcal C(m).", "A witnessed shared orbit point transfers convergence between starts without requiring equal step counts.", "Use the finite-prefix convergence equivalence for both starts and replace their common iterate using the assumed equality.", T+" "+CONV)
SC = r"Let $\mathsf S$ assert that every $n>1$ has a positive $m<n$ and $r,s\in\mathbb N$ with $T^r(n)=T^s(m)$."
add("allPositiveConverge_of_smallerCoalescence", "Universal smaller coalescence implies convergence", SC+r" Assume $\mathsf S$. Then", r"\forall n>0,\ \mathcal C(n).", "The universal smaller-coalescence premise remains unproved; this is a conditional induction criterion.", "Use strong induction on the positive start. The case 1 is immediate. For a larger start, the hypothesis supplies a smaller positive coalescing start; induction gives its convergence, and the coalescence child transfers it back.", T+" "+CONV)
add("smallerCoalescenceCriterion", "Convergence is equivalent to universal smaller coalescence", SC+r" Then", r"\bigl(\forall n>0,\ \mathcal C(n)\bigr)\iff\mathsf S.", "This exact equivalence identifies a possible proof obligation; it does not discharge that obligation.", "For the forward direction choose the smaller start 1 and a time reaching it. For the reverse direction apply the strong-induction smaller-coalescence theorem.", T+" "+CONV)
add("descentCriterion", "Shortcut convergence is equivalent to universal positive descent", r"Then", r"\bigl(\forall n>0,\ \mathcal C(n)\bigr)\iff\bigl(\forall n>1,\ \exists k>0,\ 0<T^k(n)<n\bigr).", "The right-hand side is a universal hypothesis equivalent to the conjecture, rather than an established all-start descent theorem.", "A trajectory reaching 1 supplies a positive-time descent for a start above 1. Conversely, a smaller positive forward iterate is a coalescing start, so the smaller-coalescence criterion proves the implication.", T+" "+CONV)
add("equalSlopeSmaller", "Strict comparison of affine functions with equal slopes", r"For natural coefficients $A,B,R$,", r"\bigl(\forall x\in\mathbb N,\ Ax+B<Ax+R\bigr)\iff B<R.", "This isolates the intercept boundary for equal-slope affine comparisons.", "For necessity evaluate at zero. For sufficiency add the common natural quantity to the strict intercept inequality.")
add("equalSlopeWitness", "A pair of equal-time coalescing residue families", r"For every $x\in\mathbb N$,", r"T^3(8x+5)=3x+2,\quad T^3(8x+4)=3x+2,\quad 0<8x+4<8x+5.", "This gives one explicit smaller coalescing start for each member of the first family.", "Compute the parity branch at each of the three steps for each start. Both computations end at the same affine expression; positivity and strict comparison follow from their intercepts.", T)
add("oddRun", "Exact shortcut iterate of a Mersenne-form start", r"For $h,q\in\mathbb N$ with $q>0$,", r"T^h(2^h q-1)=3^h q-1.", "This is an exact finite-prefix identity. At $h=0$ subtraction is interpreted on natural numbers as in the source.", "Induct on the length. A positive-length start is odd; its first shortcut step replaces one power of 2 by one factor of 3. Apply the induction hypothesis to the resulting positive parameter.", T)
add("shortcutIter_OOE", "Three-step odd–odd–even shortcut identity", r"For every $z\in\mathbb N$,", r"T^3(8z+3)=9z+4.", "This is the elementary block underlying the guarded burst construction.", "The three successive inputs follow odd, odd, and even branches. Substitute the corresponding affine expressions and simplify the exact divisions.", T)
add("rootDescentBurst", "Exact iterate for an arbitrary finite OOE burst", r"For $k,u\in\mathbb N$ with $u>0$,", r"T^{3k}(8^k u-5)=9^k u-5.", "The burst length is unbounded, but the statement describes only a finite prefix and does not claim descent.", "Induct on the number of three-step blocks. For a positive number of blocks, express the start in the odd–odd–even residue class and apply the three-step identity. The new parameter is multiplied by 9; the induction hypothesis completes the remaining blocks.", T)
add("rootDescent", "Guarded burst followed by halving descends below its start", r"Let $k,u,m\in\mathbb N$ be positive and assume $2^k m+5=9^k u$. Then", r"T^{4k}(8^k u-5)=m<8^k u-5.", "The displayed exit equation is essential and is not asserted for every positive start.", "The burst child computes the first 3k steps. The exit equation makes its endpoint exactly a multiple of the kth power of 2, so k halving steps reach m. The source power comparison bounds m strictly below the unchanged original start.", T)
add("rootDescentAncestor", "Guarded ancestor identity for an odd run and even padding", r"Let $e,L,q,r\in\mathbb N$, $q>0$, and $3^{L+1}q=4r+1$. Then", r"T^{e+L+2}\bigl(2^e(2^Lq-1)\bigr)=r.", "This supplies an actual forward ancestor trajectory; no size, residue, or all-root coverage claim is part of the result.", "Remove the initial e powers of two by halving. Apply the exact odd-run identity, then use the endpoint equation to evaluate the final two shortcut steps.", T)
add("rootDescent_converges_of_smaller", "Conditional convergence transfer from guarded burst descent", r"Let $k,u,m>0$ be natural numbers with $2^k m+5=9^k u$, and put $N=8^k u-5$. Assume $\mathcal C(a)$ for every natural $a$ with $0<a<N$. Then", r"\mathcal C(N).", "This is a strong-induction transfer for a guarded family; the hypothesis on all smaller starts remains explicit.", "The guarded-descent child gives a finite iterate equal to the positive smaller number m. Apply the induction premise to m and then transfer convergence through the computed finite prefix.", T+" "+CONV)

add("orbitAffine", "Exact affine identity along an actual shortcut prefix", r"For every $n,k\in\mathbb N$,", r"2^k T^k(n)=3^{q_k(n)}n+R_k(n).", "This connects the actual parity trajectory to exact integer affine coefficients.", "Induct on the prefix length. An even step doubles the denominator without changing the odd count or remainder; an odd step multiplies the numerator by 3 and adds the current denominator. These are exactly the defining recurrences.", T+" "+ORBIT)
add("mechanicalEnvelope", "Mechanical upper envelope before the first coefficient crossing", r"Let $n,k\in\mathbb N$ and assume $2^j\le3^{q_j(n)}$ for every $j<k$. Then", r"R_k(n)\le M(q_k(n)).", "The earlier coefficient barriers are explicit assumptions, so this is not an unconditional bound on all orbit prefixes.", "Induct over the actual prefix. Even steps preserve the remainder. At an odd step the prior barrier bounds its additive power of 2 by the largest dyadic power below the corresponding power of 3. The mechanical recurrence then dominates the updated remainder.", T+" "+ORBIT+" "+MECH)
add("affineQuarterCertificate", "Soundness of an arithmetic quarter-gap certificate", r"Let $n,d,a,b,C,s\in\mathbb N$ satisfy $n>0$, $a<b$, $b(n+d)=an+C$, and $4C\le sb$. Then", r"4d<s.", "This is an arithmetic certificate independent of the Collatz map and does not assert that the hypotheses hold on any orbit.", r"The affine equation gives $bd<C$ because $(b-a)n>0$. Multiplication by 4 and the certificate bound yield $4bd<sb$. Cancel the positive factor $b$.")
add("firstContractionTime", "The time of a first coefficient contraction", r"If $n,k\in\mathbb N$ and $k$ is a first coefficient contraction for $n$, then", r"k=e(q_k(n)).", "This determines the crossing time from its odd count, conditional on that first crossing existing.", "Consider the last step before the crossing. An odd last step would triple the coefficient while only doubling its denominator and so cannot cross the previous barrier. For an even last step, the last barrier and the strict crossing place the power of 3 between successive powers of 2, fixing its integer logarithm.", T+" "+ORBIT+" "+MECH+" "+FIRST)
add("mechanicalCoarseBound", "A coarse one-third bound on the mechanical remainder", r"For every $s\in\mathbb N$,", r"3M(s)\le s3^s.", "This universal numerical envelope supports a conditional first-contraction gap estimate.", "Induct on s using the mechanical recurrence. The new dyadic term is at most the power of 3 below which it is defined; combining that bound with the induction hypothesis gives the next coefficient.", MECH)
for name,den,label in [("firstContractionThirdGap",3,"one-third"),("firstContractionQuarterGap",4,"one-quarter")]:
    add(name, "A "+label+" defect bound at a first coefficient contraction", r"Let $n,k,d\in\mathbb N$, with $n>0$, and assume a first coefficient contraction at $k$ and $T^k(n)=n+d$. Then", rf"{den}d<q_k(n),\qquad d\le\left\lfloor\frac{{q_k(n)-1}}{{{den}}}\right\rfloor.", "The conclusion applies to an existing first crossing whose endpoint has not fallen below its start. It does not prove existence of a first crossing.", ("Combine the actual affine identity with the mechanical envelope and its coarse one-third bound. Strict coefficient contraction at a positive start makes the affine remainder strictly exceed the scaled defect. Cancel the power of 2 and convert the strict integer bound to the quotient bound." if den==3 else "The one-third gap ensures that the odd count is positive. Apply the universal mechanical quarter certificate to that count and then the conditional quarter-certificate theorem. Integer arithmetic converts the strict gap to the stated quotient bound."), T+" "+ORBIT+" "+MECH+" "+FIRST)
add("firstContraction_quarter_of_certificate", "First-contraction quarter gap from a supplied numerical certificate", r"Let $n,k,d\in\mathbb N$, $n>0$, with a first coefficient contraction at $k$ and $T^k(n)=n+d$. Assume $4M(q_k(n))\le q_k(n)2^{e(q_k(n))}$. Then", r"4d<q_k(n).", "This isolates the exact numerical certificate needed by the orbit argument.", "Use the first-contraction-time child to identify the denominator exponent. The affine-identity and mechanical-envelope children supply the arithmetic quarter certificate, which gives the strict defect bound.", T+" "+ORBIT+" "+MECH+" "+FIRST)
add("floorPower_mul", "The two dyadic bins for a product", r"Let $a,x,f,k\in\mathbb N$ satisfy $2^f\le a<2^{f+1}$ and $2^k\le x<2^{k+1}$. Write $F(y)=2^{\lfloor\log_2 y\rfloor}$ for positive $y$. Then", r"F(ax)=\begin{cases}2^{f+k}&ax<2^{f+k+1},\\2^{f+k+1}&ax\ge2^{f+k+1}.\end{cases}", "This converts multiplication of dyadic floor powers into one exact threshold test.", "Multiplying the given intervals places the product between the dyadic powers with exponents f+k and f+k+2. The intermediate threshold separates the only two possible integer-logarithm values.")
BLOCK=r"For $B,x\in\mathbb N$, define the normalized twelve-term numerator $N_{12}(B,x)=\sum_{i=0}^{11}3^{11-i}D_i(B,x)$. Here $f_i=\lfloor\log_2(3^i)\rfloor$, and $D_i(B,x)$ is $2^{f_i}B$ when $3^i x<2^{f_i+1}B$, and $2^{f_i+1}B$ otherwise."
add("blockNumerator12_exact_bound", "Exact uniform bound for the twelve-term normalized numerator", r"If $B>0$ and $B\le x<2B$, then", r"262144\,N_{12}(B,x)\le416200322061\,x.", "This finite phase bound is the arithmetic input to twelve-step mechanical-envelope propagation.", "Order the eleven interior thresholds of the normalized interval. In each of the twelve resulting cases every conditional numerator term is fixed as a multiple of B; the claimed bound is then an exact linear integer inequality. The checked proof covers every threshold boundary.", BLOCK)
add("mechanical_twelve_identity", "Exact twelve-step recurrence of the mechanical envelope", r"For every $s\in\mathbb N$,", r"M(s+12)=3^{12}M(s)+N_{12}\bigl(2^{\lfloor\log_2(3^s)\rfloor},3^s\bigr).", "This groups twelve scalar recurrence steps while preserving all dyadic rounding phases.", "Expand the mechanical recurrence twelve times. For each power of 3 use the two-bin dyadic-product child to express its floor power relative to the initial bin. Collecting the terms gives the defined twelve-term numerator.", MECH+" "+BLOCK)
add("mechanical_twelve_propagation", "Propagation of the mechanical envelope by twelve steps", r"Let $s\in\mathbb N$ and assume $4M(s)\le s3^s$. Then", r"4M(s+12)\le(s+12)3^{s+12}.", "A finite set of consecutive base cases can therefore cover every later index by residue modulo 12.", "Apply the exact twelve-step recurrence. Multiply the assumed initial envelope by the twelfth power of 3 and use the checked twelve-term numerator bound for the remaining contribution. The two contributions sum to the desired new coefficient.", MECH)
add("mechanical_large_bound", "The mechanical envelope for every index at least sixteen", r"For every $s\in\mathbb N$ with $s\ge16$,", r"4M(s)\le s3^s.", "This is a bound on the auxiliary mechanical sequence, not an all-start Collatz descent assertion.", "Verify the twelve base indices from 16 through 27 by exact computation. Strong induction reduces any larger index by 12 and applies the twelve-step propagation child.", MECH)
add("mechanical_fifteen_failure", "Failure of the normalized mechanical envelope at index fifteen", "At the single index $s=15$,", r"15\cdot3^{15}<4M(15).", "Together with the separate theorem for all indices at least 16, this identifies the smallest eventual threshold. This theorem alone states only the failure at 15.", "Unfold the finite recurrence through index 15 and compare the resulting natural numbers using a checked decision proof.", MECH)
add("universalMechanicalQuarterCertificate", "A mechanical quarter certificate at every positive odd count", r"For every $s\in\mathbb N$ with $s\ge1$,", r"4M(s)\le s2^{e(s)}.", "This numerical certificate supplies the hypothesis for the actual-orbit quarter-gap result.", "For indices through 15 use the exact finite certificate. For larger indices use the mechanical envelope from 16 onward and the fact that the dyadic crossing power is strictly above the corresponding power of 3.", MECH)

PALETTE=r"Let $r,B\in\mathbb N$, let $f_0,\ldots,f_{r-1}:\mathbb N\to\mathbb N$ be nondecreasing on inputs at least $B$, and let $\sigma:\mathbb N\to\{0,\ldots,r-1\}$. Let $V:\mathbb N\to\mathbb N$ satisfy $V(n)=f_{\sigma(n)}(n)$ for $n\ge B$."
add("finitePalette_path_obstruction", "A finite monotone palette cannot decrease along too long a rising path", r"Let $x:\mathbb N\to\mathbb N$ have $x_0\ge B$ and $x_k\le x_{k+1}$ for $k<r$. Then it is impossible that", r"\forall k<r,\quad V(x_{k+1})<V(x_k).", "This is a finite pigeonhole obstruction for ranks selected from monotone functions; it is independent of Collatz.", "If the rank strictly decreased at every transition, two selected indices could never coincide: monotonicity of that one function would contradict the strict rank drop. The r+1 path positions would therefore select r+1 distinct members from a set of size r, a contradiction.", PALETTE)
add("finitePaletteObstruction", "No bounded-time descent rank from a finite monotone palette", r"For any further natural threshold $B'$ and time bound $H$, the following uniform rank-descent assertion is false:", r"\neg\bigl(\forall n\ge B',\ \exists j,\ 1\le j\le H\ \land\ V(T^j(n))<V(n)\bigr).", "The obstruction concerns this finite-palette, uniformly bounded-time proof architecture. It does not imply nontermination of any Collatz orbit.", "Choose a sufficiently large Mersenne-form start with a nondecreasing prefix of length rH. If the proposed uniform descent rule held, repeatedly choose r rank-decreasing jumps of length at most H. All selected endpoints remain on that nondecreasing prefix and above both thresholds. The finite-path child contradicts r successive rank decreases.", T+" "+PALETTE)
add("mersenne_prefix_nondecreasing", "Nondecreasing prefixes of arbitrary finite Mersenne length", r"Let $L,q\in\mathbb N$ with $q>0$, and put $N=2^Lq-1$. Then", r"\forall k<L,\quad T^k(N)\le T^{k+1}(N).", "The length L is arbitrary, but the conclusion is confined to the finite initial prefix.", "The odd-run identity expresses the kth point of this prefix as twice a positive natural number minus one. Its next shortcut step is three times that number minus one, which is at least the current point.", T)
PREFIX = r"The starts $n,m\in\mathbb N$ have the same parity prefix of length $k\in\mathbb N$ when $T^i(n)\equiv T^i(m)\pmod2$ for every $i<k$."
add("parityPrefix_dvd_sub_of_le", "Equal parity prefixes force power-of-two divisibility", r"Assume equal parity prefixes of length $k$ and $n\le m$. Then", r"2^k\mid(m-n).", "The order hypothesis makes natural subtraction agree with integer subtraction.", "Induct on the prefix length. Equal first parity ensures ordered successors and an equal shorter suffix. Doubling the successor difference yields the original difference in the even case and three times it in the odd case; coprimality cancels the odd factor 3.", T+" "+PREFIX)
add("prefixCollision", "Equal shortcut parity prefixes force equal dyadic residues", r"If the parity prefixes of $n$ and $m$ agree for $k$ steps, then", r"n\equiv m\pmod{2^k}.", "This constrains finite parity-prefix collisions without a convergence assumption.", "Order the two starts, apply the power-of-two divisibility child to their difference, and translate divisibility into equality of residues. Reverse the starts in the other order case.", T+" "+PREFIX)
add("prefixSeparation", "Distinct starts with one parity prefix are dyadically separated", r"If $n\ne m$ and their parity prefixes of length $k$ agree, then", r"2^k\le|n-m|.", "The modulus supplies a quantitative separation between distinct starts with the same finite itinerary.", "The appropriate ordered difference is positive and divisible by the prefix modulus. A divisor of a positive natural number is no larger than the number, which gives the absolute-difference bound.", T+" "+PREFIX)
REF=r"For natural parameters $L,\varepsilon,z$, put $A=4z+2\varepsilon+1$, $P=2^LA-1$, and $Q=3\cdot2^{L-2}A-1$. When $L<2$, the exponent $L-2$ uses truncated natural subtraction."
GUARD=r"Assume $L\ge2$, $\varepsilon\le1$, and $\varepsilon\equiv L\pmod2$."
add("compatibleProduct_mod_four", "Parity compatibility fixes the refined product modulo four", r"Assume $\varepsilon\le1$ and $\varepsilon\equiv L\pmod2$. Then", r"3^LA\equiv1\pmod4.", "This supplies the exact two-halving guard in the refined parent construction; no lower bound on L is required.", "There are two possible values of epsilon. If it is zero, L is even and both factors have residue 1 modulo 4. If it is one, L is odd and both factors have residue 3, whose product has residue 1.", REF)
add("refinedChild_arithmetic", "The refined child is positive and strictly smaller", r"Assume $L\ge2$; no parity restriction on $\varepsilon$ is needed. Then", r"0<P,\quad0<Q<P,\quad Q=\left\lfloor\frac{3P-1}{4}\right\rfloor.", "This proves the size comparison used by the later guarded coalescence result.", "Write the positive quantity b as the product of A and the power of 2 with exponent L−2. Then the parent and child are respectively 4b−1 and 3b−1; all four assertions reduce to integer arithmetic.", REF)
add("refinedParent_iter", "The parity-compatible refined parent reaches an explicit endpoint", r"Assume $\varepsilon\le1$ and $\varepsilon\equiv L\pmod2$. Then", r"T^{L+2}(P)=\left\lfloor\frac{3^LA-1}{4}\right\rfloor.", "The endpoint identity also covers L equal to 0 or 1; no claim of positivity or a smaller child is included here.", "The exact odd-run child computes the first L steps as the power-of-3 product minus one. Parity compatibility makes that quantity divisible by 4, so the last two steps are exact halvings.", T+" "+REF)
add("refinedChild_iter", "The parity-compatible refined child reaches the same endpoint", GUARD+r" Then", r"T^L(Q)=\left\lfloor\frac{3^LA-1}{4}\right\rfloor.", "This gives the child side of the guarded coalescence construction.", "Compute the first L−2 odd steps explicitly. The product congruence determines the residue of the resulting power-of-3 multiple; its last two steps are an even step followed by an odd step and give the displayed quotient.", T+" "+REF)
add("refinedMersenneChild_coalesces", "Guarded coalescence of a refined Mersenne parent and child", GUARD+r" Then", r"T^{L+2}(P)=T^L(Q).", "This is an exact shared orbit point for one explicit guarded family; it supplies no universal selector.", "The parent-iterate child and the child-iterate child identify both sides with the same explicit quotient. Their equality gives the conclusion.", T+" "+REF)
add("refinedParent_converges_iff_child", "Refined parent and child have equivalent convergence", GUARD+r" Then", r"\mathcal C(P)\iff\mathcal C(Q).", "The result transfers convergence across the guarded shared orbit point without asserting convergence on either side.", "Apply the coalescence-convergence child to the shared point furnished by the refined parent–child coalescence theorem.", T+" "+CONV+" "+REF)
add("refinedParent_has_smaller_coalescence", "A positive smaller coalescing start for a guarded parent", GUARD+r" Then", r"\exists m\in\mathbb N,\ 0<m<P\ \land\ \exists r,s\in\mathbb N,\ T^r(P)=T^s(m).", "This witnesses the smaller-coalescence criterion on the stated family only.", "Choose the explicit child Q. The arithmetic child proves it is positive and smaller, while the coalescence child supplies the times L+2 and L.", T+" "+REF)
add("refinedParent_converges_of_smaller", "Conditional convergence of a guarded refined parent", GUARD+r" Assume additionally $\mathcal C(m)$ for every natural $m$ with $0<m<P$. Then", r"\mathcal C(P).", "This is a strong-induction application with the smaller-start hypothesis retained.", "The child is positive and smaller, so the induction premise proves its convergence. The parent–child convergence-equivalence theorem transfers that result to the parent.", T+" "+CONV+" "+REF)

CHAIN=r"Let $S$ be a finite list of segments $(k_i,A_i,D_i)$ of natural numbers, with $D_i>0$. Starting from $n$, define successive endpoints by applying $T^{k_i}$. Assume each segment satisfies $D_i(\text{endpoint}+3)\le A_i(\text{start}+3)$. Write $K=\sum_i k_i$, $A=\prod_i A_i$, and $D=\prod_i D_i$, with empty products 1."
add("shiftedEnvelope_compose", "Composition of two shifted shortcut envelopes", r"Let $n,k,l,A,B,D,E\in\mathbb N$. Assume $D(T^k(n)+3)\le A(n+3)$ and $E(T^l(T^k(n))+3)\le B(T^k(n)+3)$. Then", r"DE(T^{k+l}(n)+3)\le AB(n+3).", "This combines local bounds relative to the unchanged original start. It requires no positive-denominator hypothesis for this non-strict inequality.", "Multiply the second envelope by D, then multiply the first by B and substitute it into the result. The iteration-composition identity identifies the combined endpoint.", T)
add("excursionChainEnvelope", "Product envelope for an arbitrary finite segment list", "Under the segment assumptions,", r"D(T^K(n)+3)\le A(n+3),\qquad D>0.", "The list can have any finite length, including zero. All segment inequalities remain explicit premises.", "Induct on the list. For the empty list, the identity iterate and empty products give the claim. For a nonempty list, apply the induction result to the tail at the first endpoint, compose its envelope with the first segment, and multiply the positive denominators.", T+" "+CHAIN)
add("terminalEnvelope_compose", "Append a strict unshifted terminal envelope", r"Let $n,k,l,A,B,D,E\in\mathbb N$ with $D>0$. Assume $D(T^k(n)+3)\le A(n+3)$ and $E T^l(T^k(n))<B(T^k(n)+3)$. Then", r"DE T^{k+l}(n)<AB(n+3).", "The positivity of D preserves the terminal strict inequality during composition.", "Multiply the strict terminal bound by positive D. Bound its right side using B times the prefix envelope, then rewrite the nested iterate as the sum of the two lengths.", T)
add("excursionBudgetDescent", "A half-margin envelope forces descent below the original root", r"Let $n,k,A,D\in\mathbb N$ satisfy $n\ge3$, $D T^k(n)<A(n+3)$, and $2A\le D$. Then", r"T^k(n)<n.", "This is the numerical repayment condition for the shifted orbit envelope.", r"Since $n\ge3$, one has $n+3\le2n$. Thus the assumed strict bound is at most $2An\le Dn$, giving $D T^k(n)<Dn$. Cancellation yields strict descent.", T)
for name,conclusion,title,extra,proof in [
    ("excursionChain_terminal_descent",r"T^{K+l}(n)<n.","Finite excursion chain with a terminal budget descends","", "The chain-envelope child supplies a positive product denominator and a shifted bound. Append the terminal strict envelope, then apply the half-margin descent child with product coefficients."),
    ("excursionChain_converges_of_smaller",r"\mathcal C(n).","Conditional convergence after a finite excursion chain",r" Assume also $\mathcal C(m)$ for every $0<m<n$.","The terminal-descent child gives a smaller forward iterate. Positivity of the shortcut map ensures that iterate is positive, so the smaller-start premise gives its convergence. Transfer convergence through the finite prefix.")]:
    add(name,title,r"Let $l,B,E\in\mathbb N$ and $n\ge3$. Assume $E T^l(T^K(n))<B(T^K(n)+3)$ and $2AB\le DE$."+extra+" Then",conclusion,"The segment and terminal envelopes and cumulative budget are hypotheses; no all-root coverage is asserted.",proof,T+" "+CONV+" "+CHAIN)

ANCESTOR=r"\exists m,b\in\mathbb N,\quad 0<m<r,\quad m\equiv20\pmod{27},\quad T^b(m)=r."
add("residueAncestor", "A smaller residue-20 ancestor under a factorization guard", r"Let $v,u,r\in\mathbb N$ satisfy $v\ge13$, $u>0$, $u\not\equiv0\pmod3$, and $3^v u=4r+1$. Then", ANCESTOR, "This gives a smaller positive ancestor for roots satisfying the explicit valuation guard. It asserts no coverage of roots outside that guard.", "Write v as k+3, so k is at least 10. Apply the normalized ancestor-construction child with the unchanged root and unit parameter.", T)
add("residueAncestor_normalized", "Normalized construction of a smaller residue-20 ancestor", r"Let $k,u,r\in\mathbb N$ satisfy $k\ge10$, $u>0$, $u\not\equiv0\pmod3$, and $3^{k+3}u=4r+1$. Then", ANCESTOR, "This is the factorized ancestor construction before replacing k+3 by a single valuation parameter.", "Set x to the product of the kth power of 2 and u. It is a unit modulo 3, so there are six possible residues modulo 9. The two variable-prefix children and the refined-tail child or suitable even padding supply an ancestor in each case. The uniform power comparison at exponent at least 13 bounds every constructed ancestor strictly below r.", T)
add("residueAncestor_of_divisibility", "A smaller residue-20 ancestor from divisibility by the thirteenth power of three", r"Let $r\in\mathbb N$ satisfy $3^{13}\mid(4r+1)$. Then", ANCESTOR, "The premise is only integer divisibility; a maximal power-of-three factorization is constructed within the proof. The divisor condition remains a genuine guard.", "Take the positive quotient after dividing 4r+1 by the thirteenth power of 3. The factor-unit child expresses that quotient as a power of 3 times a positive unit. Combining the exponents yields the hypotheses of the factorized ancestor theorem.", T)
add("residueAncestor_factor_unit", "Positive naturals factor into a power of three and a unit", r"For every natural $n>0$,", r"\exists e,u\in\mathbb N,\quad u>0,\quad u\not\equiv0\pmod3,\quad3^e u=n.", "This existence lemma supplies the normalized factorization needed by the divisibility-form ancestor theorem.", "Use strong induction on n. If n is not divisible by 3, take exponent zero. Otherwise its quotient by 3 is positive and smaller; factor the quotient inductively and increase its exponent by one.")
for name,steps,coefficient in [("residueAncestor_prefix_one",3,6),("residueAncestor_prefix_two",2,9)]:
    add(name,"Variable ancestor prefix of length k plus "+str(steps), r"Let $k,u,r\in\mathbb N$ with $u>0$ and $3^{k+3}u=4r+1$. Then", rf"T^{{k+{steps}}}({coefficient}\cdot2^k u-1)=r.", "This computes a guarded forward prefix without claiming that its starting value is smaller than r.", ("Specialize the guarded ancestor identity with no initial even padding, odd-run parameter k+1, and positive unit parameter 3u. Rearranging powers recovers the given factorization and start." if steps==3 else "Specialize the guarded ancestor identity with no initial even padding, odd-run parameter k, and positive unit parameter 9u. Rearranging powers recovers the given factorization and start."), T)
for tail,coef,offset,mod,steps,mult,const,power in [(38,216,101,81,3,3,1,8),(65,432,344,81,4,3,8,16),(11,1728,74,243,6,9,38,64),(92,6912,2612,243,8,9,44,256),(173,864,614,243,5,9,10,32)]:
    add("residueAncestor_tail"+str(tail), f"Exact residue-20 tail to {tail} modulo {mod}", rf"For $a\in\mathbb N$, put $m={coef}a+{offset}$ and $z={mod}a+{tail}$. Then", rf"m>0,\quad m\equiv20\pmod{{27}},\quad T^{{{steps}}}(m)=z,\quad {mult}m+{const}={power}z,\quad m\le64z.", "This is one row of the finite tail selector. The bound by 64z is not a claim that the ancestor is smaller than z.", "Compute each of the displayed finite number of shortcut steps using its exact parity. The remaining positivity, residue, affine-certificate, and size assertions are linear integer identities or inequalities in the free nonnegative parameter.", T)
add("residueAncestor_refinedTail", "A uniform residue-20 tail for every root congruent to eleven modulo twenty-seven", r"Let $z\in\mathbb N$ satisfy $z\equiv11\pmod{27}$. Then", r"\exists m,b\in\mathbb N,\quad m>0,\quad m\equiv20\pmod{27},\quad T^b(m)=z,\quad m\le64z.", "This gives a bounded-size ancestor; strict descent relative to the later original root requires a separate power comparison.", "Split the residue class into the five disjoint classes 38 and 65 modulo 81, and 11, 92, and 173 modulo 243. The corresponding five tail children provide the required ancestor and the same coarse factor-64 bound in every case.", T)
TWO=r"Let $k,l,u,v,m$ be positive natural numbers satisfying $9^k u+1=2^{3l+1}v$ and $2^{k+l}m+5=3\cdot9^l v$. Put $N=2\cdot8^ku-5$."
add("twoBurstDescent", "Two guarded growing bursts descend below the original start", "Under these hypotheses,", r"T^{4(k+l)+2}(N)=m<N.", "Both exact arithmetic guards are assumptions. No universal choice of parameters or all-root coverage is asserted.", "Compute the first OOE burst, the intervening odd–even connector fixed by the recharge equation, and the second burst. The exit equation permits the final k+l halvings. The checked two-burst power margin absorbs the subtraction terms and proves comparison with the original start.", T+" "+TWO)
add("twoBurst_converges_of_smaller", "Conditional convergence after a guarded two-burst descent", r"Assume additionally $\mathcal C(a)$ for every natural $a$ with $0<a<N$. Then", r"\mathcal C(N).", "The convergence conclusion retains both arithmetic guards and the smaller-start induction premise.", "Use the two-burst descent child to reach m, which is positive and smaller than N. Apply the induction premise there and concatenate the finite prefix with its path to 1.", T+" "+CONV+" "+TWO)
add("twoBurst_power_margin", "Uniform coefficient margin for two burst lengths", r"For every $j,l\in\mathbb N$,", r"3\cdot9^{j+l+1}+3\cdot9^l+10\cdot8^l2^{j+l+1}<4\cdot16^{j+l+1}.", "This numerical inequality supplies slack for the guarded original-root comparison.", "Induct on j. At zero, compare the lth power of 9 with that of 16 and combine the lth powers of 8 and 2. In the induction step the right side grows by 16, while the varying left terms grow by only 9 and 2 and the remaining term is fixed.")
BLOCKS=r"Write $B=T^3$, and let $B^j$ be its j-fold iterate. A start $n$ has $m$ good blocks if $B^j(n)\equiv11\pmod{16}$ for every $j<m$."
add("BlindCollatz.AlternatingGrowth.arbitrarily_long_expansion", "Arbitrarily long finite sequences of expanding alternating blocks", r"For every natural $m>0$,", r"\exists n\in\mathbb N,\quad (\forall j<m,\ B^j(n)\equiv11\pmod{16})\ \land\ n<B^m(n).", "The starting value may depend on the finite requested length. This does not assert the existence of one infinitely expanding orbit.", r"Choose $n=16\cdot8^m-5$. The seed recurrence verifies all m good blocks and gives the final value $16\cdot9^m-5$. The strict comparison follows from $9^m>8^m$ for positive m.", T+" "+BLOCKS)
add("BlindCollatz.AlternatingGrowth.goodBlocks_each_block_grows", "Every certified alternating block strictly increases its endpoint", r"Let $m,n\in\mathbb N$ and assume that $n$ has $m$ good blocks. Then", r"\forall j<m,\quad B^j(n)<B^{j+1}(n).", "This makes the finite growth certificate local at every successive block endpoint.", "Induct on the number of good blocks. A start in residue 11 modulo 16 has the explicit three-step image 18q+13 when written as 16q+11, which is larger. The tail of the good-block certificate supports the induction step.", T+" "+BLOCKS)
add("BlindCollatz.AlternatingGrowth.odd_exponents_one_two", "Exact first and second odd-step valuation congruences", r"For every $q\in\mathbb N$,", r"3(16q+11)+1\equiv2\pmod4,\qquad3(24q+17)+1\equiv4\pmod8.", "These congruences certify exact powers of two with exponents 1 and 2 in the two odd updates.", "Expand each affine expression. The first is 48q+34, with residue 2 modulo 4; the second is 72q+52, with residue 4 modulo 8. Both calculations hold for every natural q.")
add("BlindCollatz.AlternatingGrowth.ordinary_five", "Five ordinary steps for one alternating expansion block", r"For every $q\in\mathbb N$,", r"C^5(16q+11)=18q+13.", "This computes the ordinary-map timing for the residue family, without substituting shortcut and ordinary step counts.", "The successive values are 48q+34, 24q+17, 72q+52, 36q+26, and 18q+13. Their parities select exactly the ordinary branches used in the computation.", O)
add("BlindCollatz.AlternatingGrowth.shortcut_three_eq_ordinary_five", "Three shortcut steps agree with five ordinary steps on the alternating block", r"For every $q\in\mathbb N$,", r"T^3(16q+11)=C^5(16q+11).", "This is an explicit bridge between the two iteration conventions on the stated residue family only.", "The direct three-shortcut-step formula and the five-ordinary-step child both give 18q+13. Substitution proves the equality.", T+" "+O)

DEFINITIONS={
"ArchiveAlternatingGrowth": ("Ordinary and shortcut maps for finite alternating growth", T+"\n\n"+O+"\n\n"+BLOCKS+r" For natural $m,t$, the seed family is"+"\n\n$$\n"+r"\operatorname{seed}(m,t)=16\cdot8^m t-5."+"\n$$\n\nThese definitions distinguish two iteration conventions and encode finite good-block certificates; they do not assert one infinite growing orbit."),
"ArchiveDescent": ("Ordinary Collatz iteration and universal descent predicates", O+"\n\nThe two propositions represented by this bundle are\n\n$$\n"+r"\forall n>0,\ \exists j\in\mathbb N,\ C^j(n)=1;\qquad\forall n>1,\ \exists k>0,\ C^k(n)<n."+"\n$$\n\nThey are interfaces for a separately proved equivalence. Defining these propositions supplies no proof of either universal assertion."),
"CollatzWork_InverseWordBoundaryStatement": ("Shortcut map and equal-slope comparison interfaces", T+"\n\nFor natural coefficients A, B, and R, the comparison interface is\n\n$$\n"+r"(\forall x\in\mathbb N,\ Ax+B<Ax+R)\iff B<R."+"\n$$\n\nA second interface specifies that the starts 8x+5 and 8x+4 share the value 3x+2 after three shortcut steps, with the latter positive and smaller. These propositions support finite inverse-word comparisons."),
"CollatzWork_ConvergenceStatement": ("Shortcut iteration, convergence, and induction criteria", T+" "+CONV+"\n\nThe convergence proposition is\n\n$$\n"+r"\forall n\in\mathbb N,\quad n>0\Longrightarrow\mathcal C(n)."+"\n$$\n\nThe bundle also defines universal positive forward descent, universal smaller coalescence (allowing distinct step counts and zero-length prefixes), and their proposed equivalences to universal convergence. These are propositions to be proved; the 1–2 cycle is retained by the map."),
"CollatzWork_AffineRepetitionStatement": ("Interfaces for fixed affine repetition and divisibility budgets", r"For natural coefficients $a,b,d,c$, natural-valued sequences $x,y$, and finite length $k$, the basic recurrences are"+"\n\n$$\n"+r"b y_{i+1}=a y_i,\qquad b x_{i+1}=(b+d)x_i+c\quad(i<k)."+"\n$$\n\nThe bundle states divisibility, finite repetition bounds, and exclusions of an infinite fixed recurrence under explicit coprimality, positive shifted-start, and denominator hypotheses. It also states a numerical conditional prefix-return budget. No changing-multiplier or universal-orbit claim is encoded."),
"CollatzWork_QuarterGapStatement": ("Actual-orbit affine coefficients and mechanical certificate interfaces", T+" "+ORBIT+"\n\n"+MECH+"\n\nThe intended exact affine relation is\n\n$$\n"+r"2^kT^k(n)=3^{q_k(n)}n+R_k(n)."+"\n$$\n\n"+FIRST+" The bundle defines the orbit identity, the pre-crossing mechanical envelope, arithmetic certificate soundness, and finite-range quarter-gap propositions. These statement definitions do not assert that any crossing exists."),
"CollatzWork_FirstContractionStatement": ("First-crossing time and one-third defect interfaces", MECH+" "+ORBIT+" "+FIRST+"\n\nFor a positive start with an existing first crossing and endpoint $T^k(n)=n+d$, the defect interface includes\n\n$$\n"+r"3d<q_k(n),\qquad d\le\lfloor(q_k(n)-1)/3\rfloor."+"\n$$\n\nThe other interfaces identify the first time as e of the odd count and state the coarse mechanical envelope. They package conditional statements for separate proofs."),
"CollatzWork_QuarterGapUniversalStatement": ("Universal mechanical quarter certificates and conditional orbit gaps", MECH+"\n\nThe numerical interfaces include\n\n$$\n"+r"\forall s\ge16,\ 4M(s)\le s3^s;\qquad15\cdot3^{15}<4M(15);\qquad\forall s\ge1,\ 4M(s)\le s2^{e(s)}."+"\n$$\n\nA further interface states the one-quarter defect bound for a positive shortcut orbit at an existing first coefficient contraction with a nonnegative defect. The numerical statements are universal in their indices; existence of an orbit crossing remains conditional."),
"CollatzWork_FloorPower": ("Dyadic floor power", r"For a natural number $x$, define"+"\n\n$$\n"+r"F(x)=2^{\operatorname{log2}(x)}."+"\n$$\n\nFor positive x this is the greatest power of two at most x. The natural-number convention has log2(0)=0, hence F(0)=1. This convention keeps the function total; product-bin theorems impose positive dyadic lower bounds."),
"CollatzWork_BlockArithmetic": ("Normalized twelve-term dyadic numerator", BLOCK+"\n\nThe defining sum is\n\n$$\n"+r"N_{12}(B,x)=\sum_{i=0}^{11}3^{11-i}D_i(B,x)."+"\n$$\n\nIt is an integer expression with twelve explicit threshold tests. At B equal to the dyadic floor of x, it records the additive contribution of twelve mechanical-recurrence steps."),
"CollatzWork_RefinedMersenneChild": ("Refined Mersenne parent and child families", REF+"\n\nThe family relations are\n\n$$\n"+r"P=2^L(4z+2\varepsilon+1)-1,\qquad Q=3\cdot2^{L-2}(4z+2\varepsilon+1)-1."+"\n$$\n\nThese definitions organize an explicit smaller-child construction; the parity guard is a hypothesis of later orbit theorems. The bundle also retains the elementary simp identities needed to elaborate the shared shortcut map."),
"CollatzWork_FinitePaletteObstructionStatement": ("Finite monotone palettes and bounded-time rank descent", T+" "+PALETTE+r" Given a further threshold $B'$ and horizon $H\in\mathbb N$, the interface rules out"+"\n\n$$\n"+r"\forall n\ge B',\ \exists j,\ 1\le j\le H\ \land\ V(T^j(n))<V(n)."+"\n$$\n\nThis encodes a limitation on one proof architecture. The palette is finite and its members are eventually nondecreasing; arbitrary rank functions are not covered."),
"CollatzWork_PrefixCollisionStatement": ("Actual parity prefixes and natural absolute gaps", T+"\n\nFor natural k, n, and m, define equal parity prefixes by\n\n$$\n"+r"\forall i<k,\ T^i(n)\equiv T^i(m)\pmod2."+"\n$$\n\nThe gap is (n−m)+(m−n) with natural truncated subtraction, equivalently the absolute difference. The two statement interfaces express equal residues modulo the kth power of two and the resulting separation of distinct starts."),
"CollatzWork_RootDescentStatement": ("Guarded single-burst descent and ancestor interfaces", T+"\n\nFor positive natural k, u, and m, the guarded descent interface assumes\n\n$$\n"+r"2^k m+5=9^k u"+"\n$$\n\nand specifies that 4k shortcut steps from 8^k u−5 reach the smaller value m. Separate interfaces give the finite 3k-step burst identity and a factorization-guarded ancestor identity. No universal coverage condition is built in."),
"CollatzWork_TwoBurstStatement": ("Guarded two-burst descent interface", T+" "+TWO+"\n\nThe conclusion specified by this interface is\n\n$$\n"+r"T^{4(k+l)+2}(N)=m<N."+"\n$$\n\nThe recharge and exit equations remain explicit premises; this definition neither proves the interface nor supplies its parameters for an arbitrary start."),
"CollatzWork_ResidueAncestorStatement": ("Guarded residue-20 ancestor interfaces", T+"\n\nFor a natural root r, the common conclusion is\n\n$$\n"+ANCESTOR+"\n$$\n\nOne interface assumes a factorization 4r+1=3^v u with v at least 13 and positive u not divisible by 3. The second assumes only divisibility by the thirteenth power of 3. Both retain a guard on the root, and neither asserts universal convergence."),
"CollatzWork_ExcursionBudgetStatement": ("Finite actual-orbit segments and product envelopes", T+" "+CHAIN+"\n\nThe chain-envelope interface specifies\n\n$$\n"+r"D(T^K(n)+3)\le A(n+3),\qquad D>0."+"\n$$\n\nThe bundle defines segment length and numerator/denominator products, the recursively checked local-envelope predicate, and a terminal numerical descent interface. The empty list is allowed; local envelopes and final budgets are assumptions rather than all-root coverage results.")
}

REVIEW["CollatzWork.rootDescentBurst"]["statement"] += "\n\nSubtraction is truncated on natural numbers; this matters when k=0 and u is less than 5."
REVIEW["CollatzWork.rootDescentBurst"]["explanation"] += "\n\nSubtraction is truncated on natural numbers; the zero-block case is the identity even when u is less than 5."
first_title, first_statement = DEFINITIONS["CollatzWork_FirstContractionStatement"]
DEFINITIONS["CollatzWork_FirstContractionStatement"] = (first_title, T+" "+first_statement)

def apply_review():
    for f in (ROOT / "payloads").glob("*.theorem.json"):
        d=json.loads(f.read_text()); name=d["theorem_name"]
        if name not in REVIEW: continue
        r=REVIEW[name]
        d["theorem_title"]=r["title"]; d["natural_language_statement"]=r["statement"]
        f.write_text(json.dumps(d,indent=2,ensure_ascii=False)+"\n")
    for f in (ROOT / "payloads").glob("*.definition.json"):
        d=json.loads(f.read_text()); name=d["definition_name"]
        if name not in DEFINITIONS: continue
        title, statement=DEFINITIONS[name]
        d["definition_title"]=title; d["natural_language_statement"]=statement
        d.pop("natural_language_description",None)
        if "#L" not in d["source"]:
            rel=d["source"].split("/026aa4ad4be6453a005ab950b160a9f2204c5271/")[1]
            d["source"]+="#L1-L"+str(len((ROOT.parents[2]/rel).read_text().splitlines()))
        f.write_text(json.dumps(d,indent=2,ensure_ascii=False)+"\n")
    (ROOT/"evidence"/"reviewed-proof-explanations.json").write_text(json.dumps({n:r["explanation"] for n,r in REVIEW.items()},indent=2,ensure_ascii=False)+"\n")

if __name__ == "__main__":
    apply_review()
